/* tslint:disable */
/* eslint-disable */
/**
 * NSF Data
 * NSF Data Connector provides access to any HCL Domino NSF database as well as IBM Domino NSF database (from version 9.0.1) for which Domino Access Services (DAS) are enabled. The Connector represents NSF databases, views, view entries, and documents in JSON format.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: nsf.data@databoat.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FolderOperations
 */
export interface FolderOperations {
    /**
     * Array of UNIDs of documents to add to the folder.
     * @type {Array<string>}
     * @memberof FolderOperations
     */
    add?: Array<string>;
    /**
     * Array of UNIDs of documents to remove from the folder.
     * @type {Array<string>}
     * @memberof FolderOperations
     */
    remove?: Array<string>;
}

export function FolderOperationsFromJSON(json: any): FolderOperations {
    return FolderOperationsFromJSONTyped(json, false);
}

export function FolderOperationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FolderOperations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'add': !exists(json, 'add') ? undefined : json['add'],
        'remove': !exists(json, 'remove') ? undefined : json['remove'],
    };
}

export function FolderOperationsToJSON(value?: FolderOperations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'add': value.add,
        'remove': value.remove,
    };
}


