/* tslint:disable */
/* eslint-disable */
/**
 * NSF Data
 * NSF Data Connector provides access to any HCL Domino NSF database as well as IBM Domino NSF database (from version 9.0.1) for which Domino Access Services (DAS) are enabled. The Connector represents NSF databases, views, view entries, and documents in JSON format.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: nsf.data@databoat.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ViewColumnDesign,
    ViewColumnDesignFromJSON,
    ViewColumnDesignFromJSONTyped,
    ViewColumnDesignToJSON,
} from './';

/**
 * 
 * @export
 * @interface ViewDesignResponse
 */
export interface ViewDesignResponse extends Array<ViewColumnDesign> {
}

export function ViewDesignResponseFromJSON(json: any): ViewDesignResponse {
    return ViewDesignResponseFromJSONTyped(json, false);
}

export function ViewDesignResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewDesignResponse {
    return json;
}

export function ViewDesignResponseToJSON(value?: ViewDesignResponse | null): any {
    return value;
}


