/* tslint:disable */
/* eslint-disable */
/**
 * NSF Data
 * NSF Data Connector provides access to any HCL Domino NSF database as well as IBM Domino NSF database (from version 9.0.1) for which Domino Access Services (DAS) are enabled. The Connector represents NSF databases, views, view entries, and documents in JSON format.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: nsf.data@databoat.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    DatabaseListResponse,
    DatabaseListResponseFromJSON,
    DatabaseListResponseToJSON,
} from '../models';

/**
 * 
 */
export class DatabaseListApi extends runtime.BaseAPI {

    /**
     * Gets a list of databases
     * Gets a list of databases
     */
    async getDatabaseListRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<DatabaseListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/data`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DatabaseListResponseFromJSON(jsonValue));
    }

    /**
     * Gets a list of databases
     * Gets a list of databases
     */
    async getDatabaseList(initOverrides?: RequestInit): Promise<DatabaseListResponse> {
        const response = await this.getDatabaseListRaw(initOverrides);
        return await response.value();
    }

}
